### ISSUE TITLE
Getting following error while setting up GitHub with reflow

### ISSUE THREAD

**Issue by ermauliks** [reenhanced/gitreflow#94] opened 2015-04-02 12:48 UTC
![image](https://cloud.githubusercontent.com/assets/3040988/6964209/9f049746-d964-11e4-9030-4a6a36fc22aa.png)

**Comment by nhance** [comment] 2015-04-02 12:51
Looking into this now

**Comment by nhance** [comment] 2015-04-02 13:13
@codenamev next time we work on this it looks like this may be from the `run` command on this line: https://github.com/reenhanced/gitreflow/blob/3d213a17c7f87d542ec82118e09164ab8e512b63/lib/git_reflow/git_server/git_hub.rb#L119

It appears that we lose error details because `ArgumentError` is a subclass of `StandardError`, so maybe we should be more restrictive on the type of error we rescue as well

**Comment by nhance** [comment] 2015-04-02 13:35
@ermauliks can you tell me what version of ruby you're using this with? It looks like `2.1.2` but I want to confirm

**Comment by ermauliks** [comment] 2015-04-02 13:36
@nhance correct. `2.1.2`.

**Comment by nhance** [comment] 2015-04-02 13:58
I know we saw issues with `2.1` before, if you can use `2.2.1` I think that may help but I won't know until I have a chance to run this locally

**Comment by codenamev** [comment] 2015-04-03 13:53
Fixed with `0.5.2` :tada:

**Closed** 2015-04-03 13:53 UTC

**Comment by bhavinjavia** [comment] 2015-04-06 12:25
Hi @nhance I am @ermauliks colleague and running into same issue with 2.2.1. See below.

```
➜  ~  rbenv local 2.2.1

➜  ~  ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin13]

➜  ~  gem list -d git_Reflow

*** LOCAL GEMS ***

git_reflow (0.5.2)
    Authors: Valentino Stoll, Robert Stern, Nicholas Hance
    Homepage: http://github.com/reenhanced/gitreflow
    License: MIT
    Installed at: /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0

    A better git process

➜  ~  git reflow setup
/opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/dsl.rb:226:in `verify_unused_in_option': f has already been specified as a switch in the command deliver (ArgumentError)
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/dsl.rb:220:in `block in verify_unused'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/dsl.rb:218:in `each'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/dsl.rb:218:in `verify_unused'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/dsl.rb:117:in `switch'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/command_support.rb:78:in `switch'
	from /opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/git_reflow-0.5.2/lib/git_reflow/commands/deliver.rb:6:in `block in <top (required)>'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/dsl.rb:199:in `command'
	from /opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/git_reflow-0.5.2/lib/git_reflow/commands/deliver.rb:4:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/app.rb:312:in `block in load_commands'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/app.rb:309:in `each'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/app.rb:309:in `load_commands'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/app.rb:38:in `block in commands_from'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/app.rb:36:in `each'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/gli-2.12.2/lib/gli/app.rb:36:in `commands_from'
	from /opt/boxen/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/git_reflow-0.5.2/bin/git-reflow:24:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.2.1/bin/git-reflow:23:in `load'
	from /opt/boxen/rbenv/versions/2.2.1/bin/git-reflow:23:in `<main>'
```
Notes:
1. This issue seems to occur every time after we install a newer version of ruby and install git_reflow gem.
2. I have checked ALL other ruby versions managed by rbenv and made sure git_reflow exists only on latest (2.2.1).

**Comment by codenamev** [comment] 2015-04-06 12:39
@bhavinjavia I'm looking into this now for you

**Comment by codenamev** [comment] 2015-04-06 13:03
@bhavinjavia I'm not able to reproduce that issue... I went through the process of installing that version of ruby and ensuring our gem is not installed but I have no issue running the setup command.

It is strange seeing that particular issue as the `deliver` command is the only `f` switch we use in the app.  I'm wondering if this is an issue with other GLI gems conflicting?

Can you try doing a fresh install of your ruby version and re-installing reflow?
