### ISSUE TITLE
git-reflow fork command

### ISSUE THREAD

**Issue by timraasveld** [reenhanced/gitreflow#188] opened 2016-06-15 08:36 UTC
I think it would be useful to have an option to do something like
```sh
git-reflow fork reenhanced/gitreflow add-my-awesome-feature
```
to create a fork `your_username/gitreflow` of the project `reenhanced/gitreflow` and the feature branch in `~/forks/gitreflow` (and on GitHub), and then when you type
```
git-reflow review
```
have git-reflow detect that it's a fork that should be merged in `reenhanced/gitreflow` (not sure to go how about detecting it yet)

What do you think, is this beyond the scope of git-reflow or would it make an awesome addition?

**Comment by timraasveld** [comment] 2016-06-15 08:44
Just got an idea of how to detect that it's a git-reflow fork: add an `upstream` remote which refers to the remote you would like to PR to, and an `origin` remote which is your fork on GitHub.

**Comment by codenamev** [comment] 2016-06-15 12:14
Closing as is a duplicate of #103.  The real benefits from this would only come with git-reflow fully supporting an open-source workflow.  We will most likely be moving this to an extension (via gem), but is planned for after Trello integration.  Feel free to add comments/suggestions on #103

**Closed by codenamev** 2016-06-15 12:14 UTC
