### ISSUE TITLE
option to use non-master branch by default everywhere

### ISSUE THREAD

**Issue by sshilko** [reenhanced/gitreflow#145] opened 2015-11-23 14:14 UTC
i have branch = X
X != master

I would like to do:

0. git reflow start 
1. git reflow review
2. git reflow status
3. git reflow deliver

and everything else with this branch X, atm. its possibe to

[works] git checkout X
[works] git reflow start
[works] git reflow review X
[partially-works] git reflow status X
[works] got reflow deliver X

**Comment by codenamev** [comment] 2015-11-23 17:09
Closing as this is a duplicate of #73.  We have a `git-reflow config` milestone setup that we're bundling this feature into to allow you to override some basic assumptions git-reflow makes.  Should be released in the next couple weeks.

**Closed by codenamev** 2015-11-23 17:09 UTC
